const concelhosDistrito = [
  { municipio: "Lisboa", distrito: "Lisboa" },
  { municipio: "Sintra", distrito: "Lisboa" },
  { municipio: "Cascais", distrito: "Lisboa" },
  { municipio: "Amadora", distrito: "Lisboa" },
  { municipio: "Loures", distrito: "Lisboa" },
  { municipio: "Oeiras", distrito: "Lisboa" },
  { municipio: "Mafra", distrito: "Lisboa" },
  { municipio: "Vila Franca de Xira", distrito: "Lisboa" },
  { municipio: "Almada", distrito: "Setúbal" },
  { municipio: "Seixal", distrito: "Setúbal" },
  { municipio: "Barreiro", distrito: "Setúbal" },
  { municipio: "Moita", distrito: "Setúbal" },
  { municipio: "Montijo", distrito: "Setúbal" },
  { municipio: "Setúbal", distrito: "Setúbal" },
  { municipio: "Palmela", distrito: "Setúbal" },
  { municipio: "Lisboa", distrito: "Lisboa" }, // repetido intencionalmente se necessário
  { municipio: "Porto", distrito: "Porto" },
  { municipio: "Vila Nova de Gaia", distrito: "Porto" },
  { municipio: "Matosinhos", distrito: "Porto" },
  { municipio: "Gondomar", distrito: "Porto" },
  { municipio: "Maia", distrito: "Porto" },
  { municipio: "Valongo", distrito: "Porto" },
  { municipio: "Paredes", distrito: "Porto" },
  { municipio: "Penafiel", distrito: "Porto" },
  { municipio: "Braga", distrito: "Braga" },
  { municipio: "Guimarães", distrito: "Braga" },
  { municipio: "Vila Nova de Famalicão", distrito: "Braga" },
  { municipio: "Fafe", distrito: "Braga" },
  { municipio: "Amares", distrito: "Braga" },
  { municipio: "Esposende", distrito: "Braga" },
  { municipio: "Viana do Castelo", distrito: "Viana do Castelo" },
  { municipio: "Ponte de Lima", distrito: "Viana do Castelo" },
  { municipio: "Caminha", distrito: "Viana do Castelo" },
  { municipio: "Vila Real", distrito: "Vila Real" },
  { municipio: "Peso da Régua", distrito: "Vila Real" },
  { municipio: "Bragança", distrito: "Bragança" },
  { municipio: "Mirandela", distrito: "Bragança" },
  { municipio: "Chaves", distrito: "Vila Real" },
  { municipio: "Coimbra", distrito: "Coimbra" },
  { municipio: "Figueira da Foz", distrito: "Coimbra" },
  { municipio: "Cantanhede", distrito: "Coimbra" },
  { municipio: "Leiria", distrito: "Leiria" },
  { municipio: "Pombal", distrito: "Leiria" },
  { municipio: "Marinha Grande", distrito: "Leiria" },
  { municipio: "Santarém", distrito: "Santarém" },
  { municipio: "Tomar", distrito: "Santarém" },
  { municipio: "Abrantes", distrito: "Santarém" },
  { municipio: "Portalegre", distrito: "Portalegre" },
  { municipio: "Elvas", distrito: "Portalegre" },
  { municipio: "Évora", distrito: "Évora" },
  { municipio: "Vendas Novas", distrito: "Évora" },
  { municipio: "Beja", distrito: "Beja" },
  { municipio: "Serpa", distrito: "Beja" },
  { municipio: "Faro", distrito: "Faro" },
  { municipio: "Albufeira", distrito: "Faro" },
  { municipio: "Lagos", distrito: "Faro" },
  { municipio: "Portimão", distrito: "Faro" },
  { municipio: "Vila Real de Santo António", distrito: "Faro" },
  { municipio: "Viseu", distrito: "Viseu" },
  { municipio: "Lamego", distrito: "Viseu" },
  { municipio: "Mangualde", distrito: "Viseu" },
  { municipio: "Castelo Branco", distrito: "Castelo Branco" },
  { municipio: "Covilhã", distrito: "Castelo Branco" },
  { municipio: "Fundão", distrito: "Castelo Branco" },
  { municipio: "Guarda", distrito: "Guarda" },
  { municipio: "Figueira de Castelo Rodrigo", distrito: "Guarda" },
  { municipio: "Seia", distrito: "Guarda" },
  { municipio: "Covilhã", distrito: "Castelo Branco" },
  { municipio: "Sertã", distrito: "Castelo Branco" },
  { municipio: "Idanha-a-Nova", distrito: "Castelo Branco" },
  { municipio: "Vila Nova de Foz Côa", distrito: "Guarda" },
  { municipio: "Mêda", distrito: "Guarda" },
  { municipio: "Trancoso", distrito: "Guarda" },
  { municipio: "Almeida", distrito: "Guarda" },
  { municipio: "Sabugal", distrito: "Guarda" },
  { municipio: "Sever do Vouga", distrito: "Aveiro" },
  { municipio: "Oliveira de Azeméis", distrito: "Aveiro" },
  { municipio: "Espinho", distrito: "Aveiro" },
  { municipio: "Aveiro", distrito: "Aveiro" },
  { municipio: "Ílhavo", distrito: "Aveiro" },
  { municipio: "Ovar", distrito: "Aveiro" },
  { municipio: "Santa Maria da Feira", distrito: "Aveiro" },
  { municipio: "Estarreja", distrito: "Aveiro" },
  { municipio: "Arouca", distrito: "Aveiro" },
  { municipio: "Vagos", distrito: "Aveiro" },
  { municipio: "Albergaria-a-Velha", distrito: "Aveiro" },
  { municipio: "Anadia", distrito: "Aveiro" },
  { municipio: "Águeda", distrito: "Aveiro" },
  { municipio: "Mealhada", distrito: "Aveiro" },
  { municipio: "Oliveira do Bairro", distrito: "Aveiro" },
  { municipio: "Vila Nova de Paiva", distrito: "Viseu" },
  { municipio: "Carregal do Sal", distrito: "Viseu" },
  { municipio: "Santa Comba Dão", distrito: "Viseu" },
  { municipio: "Funchal", distrito: "Madeira" },
  { municipio: "Santa Cruz", distrito: "Madeira" },
  { municipio: "Câmara de Lobos", distrito: "Madeira" },
  { municipio: "Machico", distrito: "Madeira" },
  { municipio: "Santana", distrito: "Madeira" },
  { municipio: "Porto Moniz", distrito: "Madeira" },
  { municipio: "Calheta", distrito: "Madeira" },
  { municipio: "Ponta do Sol", distrito: "Madeira" },
  { municipio: "São Vicente", distrito: "Madeira" },
  { municipio: "Porto Santo", distrito: "Madeira" },
  { municipio: "Paul do Mar", distrito: "Madeira" },
  { municipio: "Ponta Delgada", distrito: "Açores" },
  { municipio: "Ribeira Grande", distrito: "Açores" },
  { municipio: "Lagoa", distrito: "Açores" },
  { municipio: "Vila Franca do Campo", distrito: "Açores" },
  { municipio: "Nordeste", distrito: "Açores" },
  { municipio: "Povoação", distrito: "Açores" },
  { municipio: "Angra do Heroísmo", distrito: "Açores" },
  { municipio: "Praia da Vitória", distrito: "Açores" },
  { municipio: "Vila do Porto", distrito: "Açores" }
];
