const concelhosDistrito = [
  { municipio: "Lisboa", distrito: "Lisboa" },
  { municipio: "Amadora", distrito: "Lisboa" },
  { municipio: "Oeiras", distrito: "Lisboa" },
  { municipio: "Cascais", distrito: "Lisboa" },
  { municipio: "Sintra", distrito: "Lisboa" },
  { municipio: "Loures", distrito: "Lisboa" },
  { municipio: "Mafra", distrito: "Lisboa" },
  { municipio: "Vila Franca de Xira", distrito: "Lisboa" },
  { municipio: "Almada", distrito: "Setúbal" },
  { municipio: "Seixal", distrito: "Setúbal" },
  { municipio: "Barreiro", distrito: "Setúbal" },
  { municipio: "Moita", distrito: "Setúbal" },
  { municipio: "Montijo", distrito: "Setúbal" },
  { municipio: "Palmela", distrito: "Setúbal" },
  { municipio: "Setúbal", distrito: "Setúbal" },
  { municipio: "Porto", distrito: "Porto" },
  { municipio: "Vila Nova de Gaia", distrito: "Porto" },
  { municipio: "Matosinhos", distrito: "Porto" },
  { municipio: "Gondomar", distrito: "Porto" },
  { municipio: "Maia", distrito: "Porto" },
  { municipio: "Valongo", distrito: "Porto" },
  { municipio: "Paredes", distrito: "Porto" },
  { municipio: "Penafiel", distrito: "Porto" },
  { municipio: "Braga", distrito: "Braga" },
  { municipio: "Guimarães", distrito: "Braga" },
  { municipio: "Vila Nova de Famalicão", distrito: "Braga" },
  { municipio: "Fafe", distrito: "Braga" },
  { municipio: "Amares", distrito: "Braga" },
  { municipio: "Esposende", distrito: "Braga" },
  { municipio: "Viana do Castelo", distrito: "Viana do Castelo" },
  { municipio: "Ponte de Lima", distrito: "Viana do Castelo" },
  { municipio: "Caminha", distrito: "Viana do Castelo" },
  { municipio: "Vila Real", distrito: "Vila Real" },
  { municipio: "Peso da Régua", distrito: "Vila Real" },
  { municipio: "Chaves", distrito: "Vila Real" },
  { municipio: "Bragança", distrito: "Bragança" },
  { municipio: "Mirandela", distrito: "Bragança" },
  { municipio: "Vila Pouca de Aguiar", distrito: "Vila Real" },
  { municipio: "Alijó", distrito: "Vila Real" },
  { municipio: "Montalegre", distrito: "Vila Real" },
  { municipio: "Boticas", distrito: "Vila Real" },
  { municipio: "Valpaços", distrito: "Vila Real" },
  { municipio: "Murça", distrito: "Vila Real" },
  { municipio: "Sabrosa", distrito: "Vila Real" },
  { municipio: "Carrazeda de Ansiães", distrito: "Bragança" },
  { municipio: "Freixo de Espada à Cinta", distrito: "Bragança" },
  { municipio: "Vimioso", distrito: "Bragança" },
  { municipio: "Mogadouro", distrito: "Bragança" },
  { municipio: "Macedo de Cavaleiros", distrito: "Bragança" },
  { municipio: "Mirandela", distrito: "Bragança" },
  { municipio: "Vila Flor", distrito: "Bragança" },
  { municipio: "Alfândega da Fé", distrito: "Bragança" },
  { municipio: "Valpaços", distrito: "Vila Real" },
  { municipio: "Peso da Régua", distrito: "Vila Real" },
  { municipio: "Mesão Frio", distrito: "Vila Real" },
  { municipio: "Santa Marta de Penaguião", distrito: "Vila Real" },
  { municipio: "Sabrosa", distrito: "Vila Real" },
  { municipio: "Vila Real", distrito: "Vila Real" }
];
concelhosDistrito.push(
  { municipio: "Chaves", distrito: "Vila Real" },
  { municipio: "Montalegre", distrito: "Vila Real" },
  { municipio: "Boticas", distrito: "Vila Real" },
  { municipio: "Valpaços", distrito: "Vila Real" },
  { municipio: "Murça", distrito: "Vila Real" },
  { municipio: "Vila Pouca de Aguiar", distrito: "Vila Real" },
  { municipio: "Alijó", distrito: "Vila Real" },
  { municipio: "Sabrosa", distrito: "Vila Real" },
  { municipio: "Santa Marta de Penaguião", distrito: "Vila Real" },
  { municipio: "Mesão Frio", distrito: "Vila Real" },
  { municipio: "Peso da Régua", distrito: "Vila Real" },
  { municipio: "Vila Nova de Foz Côa", distrito: "Guarda" },
  { municipio: "Seia", distrito: "Guarda" },
  { municipio: "Gouveia", distrito: "Guarda" },
  { municipio: "Mêda", distrito: "Guarda" },
  { municipio: "Trancoso", distrito: "Guarda" },
  { municipio: "Guarda", distrito: "Guarda" },
  { municipio: "Pinhel", distrito: "Guarda" },
  { municipio: "Figueira de Castelo Rodrigo", distrito: "Guarda" },
  { municipio: "Almeida", distrito: "Guarda" },
  { municipio: "Sabugal", distrito: "Guarda" },
  { municipio: "Celorico da Beira", distrito: "Guarda" },
  { municipio: "Fornos de Algodres", distrito: "Guarda" },
  { municipio: "Aguiar da Beira", distrito: "Guarda" },
  { municipio: "Vila Nova de Paiva", distrito: "Viseu" },
  { municipio: "Carregal do Sal", distrito: "Viseu" },
  { municipio: "Mangualde", distrito: "Viseu" },
  { municipio: "Sátão", distrito: "Viseu" },
  { municipio: "Nelas", distrito: "Viseu" },
  { municipio: "Tondela", distrito: "Viseu" },
  { municipio: "Viseu", distrito: "Viseu" },
  { municipio: "Santa Comba Dão", distrito: "Viseu" },
  { municipio: "Oliveira de Frades", distrito: "Viseu" },
  { municipio: "Vouzela", distrito: "Viseu" },
  { municipio: "Sever do Vouga", distrito: "Aveiro" },
  { municipio: "Águeda", distrito: "Aveiro" },
  { municipio: "Albergaria-a-Velha", distrito: "Aveiro" },
  { municipio: "Anadia", distrito: "Aveiro" },
  { municipio: "Aveiro", distrito: "Aveiro" },
  { municipio: "Vagos", distrito: "Aveiro" },
  { municipio: "Oliveira do Bairro", distrito: "Aveiro" },
  { municipio: "Ílhavo", distrito: "Aveiro" },
  { municipio: "Estarreja", distrito: "Aveiro" },
  { municipio: "Ovar", distrito: "Aveiro" },
  { municipio: "Santa Maria da Feira", distrito: "Aveiro" },
  { municipio: "Espinho", distrito: "Aveiro" },
  { municipio: "Coimbra", distrito: "Coimbra" },
  { municipio: "Figueira da Foz", distrito: "Coimbra" },
  { municipio: "Cantanhede", distrito: "Coimbra" },
  { municipio: "Condeixa-a-Nova", distrito: "Coimbra" },
  { municipio: "Montemor-o-Velho", distrito: "Coimbra" },
  { municipio: "Oliveira do Hospital", distrito: "Coimbra" },
  { municipio: "Penacova", distrito: "Coimbra" },
  { municipio: "Soure", distrito: "Coimbra" },
  { municipio: "Mira", distrito: "Coimbra" },
  { municipio: "Lousã", distrito: "Coimbra" },
  { municipio: "Arganil", distrito: "Coimbra" },
  { municipio: "Góis", distrito: "Coimbra" },
  { municipio: "Tábua", distrito: "Coimbra" },
  { municipio: "Vila Nova de Poiares", distrito: "Coimbra" }
);
concelhosDistrito.push(
  { municipio: "Penela", distrito: "Coimbra" },
  { municipio: "Alvaiázere", distrito: "Leiria" },
  { municipio: "Ansião", distrito: "Leiria" },
  { municipio: "Batalha", distrito: "Leiria" },
  { municipio: "Bombarral", distrito: "Leiria" },
  { municipio: "Caldas da Rainha", distrito: "Leiria" },
  { municipio: "Castanheira de Pera", distrito: "Leiria" },
  { municipio: "Figueiró dos Vinhos", distrito: "Leiria" },
  { municipio: "Leiria", distrito: "Leiria" },
  { municipio: "Marinha Grande", distrito: "Leiria" },
  { municipio: "Óbidos", distrito: "Leiria" },
  { municipio: "Pedrógão Grande", distrito: "Leiria" },
  { municipio: "Alcobaça", distrito: "Leiria" },
  { municipio: "Nazaré", distrito: "Leiria" },
  { municipio: "Pombal", distrito: "Leiria" },
  { municipio: "Porto de Mós", distrito: "Leiria" },
  { municipio: "Ourém", distrito: "Santarém" },
  { municipio: "Abrantes", distrito: "Santarém" },
  { municipio: "Alcanena", distrito: "Santarém" },
  { municipio: "Almeirim", distrito: "Santarém" },
  { municipio: "Benavente", distrito: "Santarém" },
  { municipio: "Cartaxo", distrito: "Santarém" },
  { municipio: "Chamusca", distrito: "Santarém" },
  { municipio: "Coruche", distrito: "Santarém" },
  { municipio: "Golegã", distrito: "Santarém" },
  { municipio: "Rio Maior", distrito: "Santarém" },
  { municipio: "Salvaterra de Magos", distrito: "Santarém" },
  { municipio: "Santarém", distrito: "Santarém" },
  { municipio: "Sardoal", distrito: "Santarém" },
  { municipio: "Tomar", distrito: "Santarém" },
  { municipio: "Vila Nova da Barquinha", distrito: "Santarém" },
  { municipio: "Torres Novas", distrito: "Santarém" },
  { municipio: "Vila de Rei", distrito: "Castelo Branco" },
  { municipio: "Castelo Branco", distrito: "Castelo Branco" },
  { municipio: "Covilhã", distrito: "Castelo Branco" },
  { municipio: "Fundão", distrito: "Castelo Branco" },
  { municipio: "Idanha-a-Nova", distrito: "Castelo Branco" },
  { municipio: "Belmonte", distrito: "Castelo Branco" },
  { municipio: "Penamacor", distrito: "Castelo Branco" },
  { municipio: "Proença-a-Nova", distrito: "Castelo Branco" },
  { municipio: "Oleiros", distrito: "Castelo Branco" },
  { municipio: "Vila Velha de Ródão", distrito: "Castelo Branco" },
  { municipio: "Vila Velha de Ródão", distrito: "Castelo Branco" },
  { municipio: "Sertã", distrito: "Castelo Branco" },
  { municipio: "Abrantes", distrito: "Santarém" },
  { municipio: "Almeirim", distrito: "Santarém" },
  { municipio: "Torres Vedras", distrito: "Lisboa" },
  { municipio: "Alenquer", distrito: "Lisboa" },
  { municipio: "Cadaval", distrito: "Lisboa" },
  { municipio: "Azambuja", distrito: "Lisboa" },
  { municipio: "Vila Franca de Xira", distrito: "Lisboa" },
  { municipio: "Loures", distrito: "Lisboa" },
  { municipio: "Mafra", distrito: "Lisboa" },
  { municipio: "Sintra", distrito: "Lisboa" },
  { municipio: "Odivelas", distrito: "Lisboa" },
  { municipio: "Lisboa", distrito: "Lisboa" },
  { municipio: "Amadora", distrito: "Lisboa" },
  { municipio: "Oeiras", distrito: "Lisboa" },
  { municipio: "Cascais", distrito: "Lisboa" },
  { municipio: "Almada", distrito: "Setúbal" },
  { municipio: "Seixal", distrito: "Setúbal" },
  { municipio: "Barreiro", distrito: "Setúbal" },
  { municipio: "Moita", distrito: "Setúbal" },
  { municipio: "Montijo", distrito: "Setúbal" },
  { municipio: "Palmela", distrito: "Setúbal" },
  { municipio: "Setúbal", distrito: "Setúbal" }
);
concelhosDistrito.push(
  { municipio: "Sines", distrito: "Setúbal" },
  { municipio: "Grândola", distrito: "Setúbal" },
  { municipio: "Odemira", distrito: "Beja" },
  { municipio: "Aljustrel", distrito: "Beja" },
  { municipio: "Almodôvar", distrito: "Beja" },
  { municipio: "Alvito", distrito: "Beja" },
  { municipio: "Barrancos", distrito: "Beja" },
  { municipio: "Beja", distrito: "Beja" },
  { municipio: "Castro Verde", distrito: "Beja" },
  { municipio: "Cuba", distrito: "Beja" },
  { municipio: "Ferreira do Alentejo", distrito: "Beja" },
  { municipio: "Mértola", distrito: "Beja" },
  { municipio: "Moura", distrito: "Beja" },
  { municipio: "Odemira", distrito: "Beja" },
  { municipio: "Ourique", distrito: "Beja" },
  { municipio: "Serpa", distrito: "Beja" },
  { municipio: "Vidigueira", distrito: "Beja" },
  { municipio: "Évora", distrito: "Évora" },
  { municipio: "Arraiolos", distrito: "Évora" },
  { municipio: "Alandroal", distrito: "Évora" },
  { municipio: "Montemor-o-Novo", distrito: "Évora" },
  { municipio: "Viana do Alentejo", distrito: "Évora" },
  { municipio: "Redondo", distrito: "Évora" },
  { municipio: "Reguengos de Monsaraz", distrito: "Évora" },
  { municipio: "Vila Viçosa", distrito: "Évora" },
  { municipio: "Portel", distrito: "Évora" },
  { municipio: "Estremoz", distrito: "Évora" },
  { municipio: "Borba", distrito: "Évora" },
  { municipio: "Vila Viçosa", distrito: "Évora" },
  { municipio: "Alcácer do Sal", distrito: "Setúbal" },
  { municipio: "Grândola", distrito: "Setúbal" },
  { municipio: "Santiago do Cacém", distrito: "Setúbal" },
  { municipio: "Odemira", distrito: "Beja" },
  { municipio: "Alcoutim", distrito: "Faro" },
  { municipio: "Aljezur", distrito: "Faro" },
  { municipio: "Castro Marim", distrito: "Faro" },
  { municipio: "Lagos", distrito: "Faro" },
  { municipio: "Loulé", distrito: "Faro" },
  { municipio: "Monchique", distrito: "Faro" },
  { municipio: "Olhão", distrito: "Faro" },
  { municipio: "Portimão", distrito: "Faro" },
  { municipio: "São Brás de Alportel", distrito: "Faro" },
  { municipio: "Silves", distrito: "Faro" },
  { municipio: "Tavira", distrito: "Faro" },
  { municipio: "Vila do Bispo", distrito: "Faro" },
  { municipio: "Vila Real de Santo António", distrito: "Faro" },
  { municipio: "Albufeira", distrito: "Faro" },
  { municipio: "Faro", distrito: "Faro" },
  { municipio: "Portimão", distrito: "Faro" },
  { municipio: "Loulé", distrito: "Faro" },
  { municipio: "Silves", distrito: "Faro" },
  { municipio: "Monchique", distrito: "Faro" },
  { municipio: "Vila do Bispo", distrito: "Faro" },
  { municipio: "Aljezur", distrito: "Faro" },
  { municipio: "Tavira", distrito: "Faro" },
  { municipio: "Olhão", distrito: "Faro" },
  { municipio: "São Brás de Alportel", distrito: "Faro" },
  { municipio: "Lagos", distrito: "Faro" },
  { municipio: "Portimão", distrito: "Faro" },
  { municipio: "Faro", distrito: "Faro" }
);
concelhosDistrito.push(
  // Madeira (11 concelhos)
  { municipio: "Funchal", distrito: "Madeira" },
  { municipio: "Santa Cruz", distrito: "Madeira" },
  { municipio: "Machico", distrito: "Madeira" },
  { municipio: "Santana", distrito: "Madeira" },
  { municipio: "São Vicente", distrito: "Madeira" },
  { municipio: "Calheta", distrito: "Madeira" },
  { municipio: "Porto Moniz", distrito: "Madeira" },
  { municipio: "Ponta do Sol", distrito: "Madeira" },
  { municipio: "Ribeira Brava", distrito: "Madeira" },
  { municipio: "Câmara de Lobos", distrito: "Madeira" },
  { municipio: "Porto Santo", distrito: "Madeira" },
  // Açores (19 concelhos)
  { municipio: "Ponta Delgada", distrito: "Açores" },
  { municipio: "Lagoa", distrito: "Açores" },
  { municipio: "Ribeira Grande", distrito: "Açores" },
  { municipio: "Vila Franca do Campo", distrito: "Açores" },
  { municipio: "Nordeste", distrito: "Açores" },
  { municipio: "Povoação", distrito: "Açores" },
  { municipio: "Horta", distrito: "Açores" },
  { municipio: "Madalen", distrito: "Açores" }, // corrigir se necessário
  { municipio: "Angra do Heroísmo", distrito: "Açores" },
  { municipio: "Praia da Vitória", distrito: "Açores" },
  { municipio: "Vila do Porto", distrito: "Açores" },
  { municipio: "Santa Cruz da Graciosa", distrito: "Açores" },
  { municipio: "São Roque do Pico", distrito: "Açores" },
  { municipio: "Lajes do Pico", distrito: "Açores" },
  { municipio: "Madalena do Pico", distrito: "Açores" },
  { municipio: "Velas", distrito: "Açores" },
  { municipio: "Calheta das Flores", distrito: "Açores" },
  { municipio: "Lajes das Flores", distrito: "Açores" },
  { municipio: "Corvo", distrito: "Açores" }
);
]
