const concelhosDistrito = [
  { municipio:"Abrantes", distrito:"Santarém" },
  { municipio:"Aguiar da Beira", distrito:"Guarda" },
  { municipio:"Alandroal", distrito:"Évora" },
  { municipio:"Albergaria-a-Velha", distrito:"Aveiro" },
  { municipio:"Albufeira", distrito:"Faro" },
  { municipio:"Alcanena", distrito:"Santarém" },
  { municipio:"Alcobaça", distrito:"Leiria" },
  { municipio:"Alcochete", distrito:"Setúbal" },
  { municipio:"Alcoutim", distrito:"Faro" },
  { municipio:"Alcácer do Sal", distrito:"Setúbal" },
  { municipio:"Alenquer", distrito:"Lisboa" },
  { municipio:"Alfândega da Fé", distrito:"Bragança" },
  { municipio:"Alijó", distrito:"Vila Real" },
  { municipio:"Aljezur", distrito:"Faro" },
  { municipio:"Aljustrel", distrito:"Beja" },
  { municipio:"Almada", distrito:"Setúbal" },
  { municipio:"Almeida", distrito:"Guarda" },
  { municipio:"Almeirim", distrito:"Santarém" },
  { municipio:"Almodôvar", distrito:"Beja" },
  { municipio:"Alpiarça", distrito:"Santarém" },
  { municipio:"Alter do Chão", distrito:"Portalegre" },
  { municipio:"Alvaiázere", distrito:"Leiria" },
  { municipio:"Alvito", distrito:"Beja" },
  { municipio:"Amadora", distrito:"Lisboa" },
  { municipio:"Amarante", distrito:"Porto" },
  { municipio:"Amares", distrito:"Braga" },
  { municipio:"Anadia", distrito:"Aveiro" },
  { municipio:"Angra do Heroísmo", distrito:"Açores" },
  { municipio:"Ansião", distrito:"Leiria" },
  { municipio:"Arcos de Valdevez", distrito:"Viana do Castelo" },
  { municipio:"Arganil", distrito:"Coimbra" },
  { municipio:"Armamar", distrito:"Viseu" },
  { municipio:"Arouca", distrito:"Aveiro" },
  { municipio:"Arraiolos", distrito:"Évora" },
  { municipio:"Arronches", distrito:"Portalegre" },
  { municipio:"Arruda dos Vinhos", distrito:"Lisboa" },
  { municipio:"Aveiro", distrito:"Aveiro" },
  { municipio:"Avis", distrito:"Portalegre" },
  { municipio:"Azambuja", distrito:"Lisboa" },
  { municipio:"Baião", distrito:"Porto" },
  { municipio:"Barcelos", distrito:"Braga" },
  { municipio:"Barrancos", distrito:"Beja" },
  { municipio:"Barreiro", distrito:"Setúbal" },
  { municipio:"Batalha", distrito:"Leiria" },
  { municipio:"Beja", distrito:"Beja" },
  { municipio:"Belmonte", distrito:"Castelo Branco" },
  { municipio:"Benavente", distrito:"Santarém" },
  { municipio:"Bombarral", distrito:"Leiria" },
  { municipio:"Borba", distrito:"Évora" },
  { municipio:"Boticas", distrito:"Vila Real" },
  { municipio:"Braga", distrito:"Braga" },
  { municipio:"Bragança", distrito:"Bragança" },
  { municipio:"Cabeceiras de Basto", distrito:"Braga" },
  { municipio:"Cadaval", distrito:"Lisboa" },
  { municipio:"Caldas da Rainha", distrito:"Leiria" },
  { municipio:"Calheta", distrito:"Madeira" },
  { municipio:"Calheta", distrito:"Açores" },
  { municipio:"Caminha", distrito:"Viana do Castelo" },
  { municipio:"Campo Maior", distrito:"Portalegre" }
];
concelhosDistrito.push(
  { municipio:"Carrazeda de Ansiães", distrito:"Bragança" },
  { municipio:"Carregal do Sal", distrito:"Viseu" },
  { municipio:"Cascais", distrito:"Lisboa" },
  { municipio:"Castanheira de Pera", distrito:"Leiria" },
  { municipio:"Castelo Branco", distrito:"Castelo Branco" },
  { municipio:"Castro Daire", distrito:"Viseu" },
  { municipio:"Castro Marim", distrito:"Faro" },
  { municipio:"Castro Verde", distrito:"Beja" },
  { municipio:"Celorico da Beira", distrito:"Guarda" },
  { municipio:"Celorico de Basto", distrito:"Braga" },
  { municipio:"Chaves", distrito:"Vila Real" },
  { municipio:"Cinfães", distrito:"Viseu" },
  { municipio:"Coimbra", distrito:"Coimbra" },
  { municipio:"Condeixa-a-Nova", distrito:"Coimbra" },
  { municipio:"Constância", distrito:"Santarém" },
  { municipio:"Coruche", distrito:"Santarém" },
  { municipio:"Covilhã", distrito:"Castelo Branco" },
  { municipio:"Crato", distrito:"Portalegre" },
  { municipio:"Cuba", distrito:"Beja" },
  { municipio:"Curtis", distrito:"Braga" },
  { municipio:"Elvas", distrito:"Portalegre" },
  { municipio:"Entroncamento", distrito:"Santarém" },
  { municipio:"Espinho", distrito:"Aveiro" },
  { municipio:"Esposende", distrito:"Braga" },
  { municipio:"Estarreja", distrito:"Aveiro" },
  { municipio:"Estremoz", distrito:"Évora" },
  { municipio:"Évora", distrito:"Évora" },
  { municipio:"Fafe", distrito:"Braga" },
  { municipio:"Fajões", distrito:"Aveiro" },
  { municipio:"Famalicão, Vila Nova de", distrito:"Braga" },
  { municipio:"Faro", distrito:"Faro" },
  { municipio:"Felgueiras", distrito:"Porto" },
  { municipio:"Ferreira do Alentejo", distrito:"Beja" },
  { municipio:"Figueira da Foz", distrito:"Coimbra" },
  { municipio:"Figueira de Castelo Rodrigo", distrito:"Guarda" },
  { municipio:"Figueiró dos Vinhos", distrito:"Leiria" },
  { municipio:"Fornos de Algodres", distrito:"Guarda" },
  { municipio:"Freixo de Espada à Cinta", distrito:"Bragança" },
  { municipio:"Funchal", distrito:"Madeira" },
  { municipio:"Gavião", distrito:"Portalegre" },
  { municipio:"Góis", distrito:"Coimbra" },
  { municipio:"Golegã", distrito:"Santarém" },
  { municipio:"Gondomar", distrito:"Porto" },
  { municipio:"Gouveia", distrito:"Guarda" },
  { municipio:"Guarda", distrito:"Guarda" },
  { municipio:"Guimarães", distrito:"Braga" },
  { municipio:"Horta", distrito:"Açores" },
  { municipio:"Ílhavo", distrito:"Aveiro" },
  { municipio:"Lagoa", distrito:"Açores" },
  { municipio:"Lagos", distrito:"Faro" },
  { municipio:"Lajes das Flores", distrito:"Açores" },
  { municipio:"Lajes do Pico", distrito:"Açores" },
  { municipio:"Lamego", distrito:"Viseu" },
  { municipio:"Leiria", distrito:"Leiria" },
  { municipio:"Lisboa", distrito:"Lisboa" },
  { municipio:"Lousã", distrito:"Coimbra" },
  { municipio:"Loures", distrito:"Lisboa" },
  { municipio:"Loures", distrito:"Lisboa" },
  { municipio:"Loulé", distrito:"Faro" },
  { municipio:"Macau", distrito:"Lisboa" },
  { municipio:"Macedo de Cavaleiros", distrito:"Bragança" },
  { municipio:"Madalena", distrito:"Açores" },
  { municipio:"Mafra", distrito:"Lisboa" }
);
concelhosDistrito.push(
  { municipio:"Manteigas", distrito:"Guarda" },
  { municipio:"Marinha Grande", distrito:"Leiria" },
  { municipio:"Mação", distrito:"Santarém" },
  { municipio:"Mangualde", distrito:"Viseu" },
  { municipio:"Mértola", distrito:"Beja" },
  { municipio:"Mesão Frio", distrito:"Vila Real" },
  { municipio:"Miranda do Douro", distrito:"Bragança" },
  { municipio:"Mirandela", distrito:"Bragança" },
  { municipio:"Moimenta da Beira", distrito:"Viseu" },
  { municipio:"Moimenta de Maceira Dão", distrito:"Viseu" },
  { municipio:"Mondim de Basto", distrito:"Vila Real" },
  { municipio:"Monchique", distrito:"Faro" },
  { municipio:"Montalegre", distrito:"Vila Real" },
  { municipio:"Montemor-o-Novo", distrito:"Évora" },
  { municipio:"Montemor-o-Velho", distrito:"Coimbra" },
  { municipio:"Montijo", distrito:"Setúbal" },
  { municipio:"Mora", distrito:"Évora" },
  { municipio:"Mortágua", distrito:"Viseu" },
  { municipio:"Moura", distrito:"Beja" },
  { municipio:"Murça", distrito:"Vila Real" },
  { municipio:"Mação", distrito:"Santarém" },
  { municipio:"Macedo de Cavaleiros", distrito:"Bragança" },
  { municipio:"Madalena do Pico", distrito:"Açores" },
  { municipio:"Madalena", distrito:"Açores" },
  { municipio:"Monção", distrito:"Viana do Castelo" },
  { municipio:"Melgaço", distrito:"Viana do Castelo" },
  { municipio:"Mealhada", distrito:"Aveiro" },
  { municipio:"Moimenta da Serra", distrito:"Guarda" },
  { municipio:"Moura", distrito:"Beja" },
  { municipio:"Manteigas", distrito:"Guarda" },
  { municipio:"Murtosa", distrito:"Aveiro" },
  { municipio:"Mesquita", distrito:"Lisboa" },
  { municipio:"Mafra", distrito:"Lisboa" },
  { municipio:"Mangualde", distrito:"Viseu" },
  { municipio:"Miranda do Corvo", distrito:"Coimbra" },
  { municipio:"Montalegre", distrito:"Vila Real" },
  { municipio:"Moura", distrito:"Beja" },
  { municipio:"Mação", distrito:"Santarém" },
  { municipio:"Madalena do Pico", distrito:"Açores" },
  { municipio:"Madalena", distrito:"Açores" },
  { municipio:"Mafra", distrito:"Lisboa" },
  { municipio:"Moura", distrito:"Beja" },
  { municipio:"Moimenta da Beira", distrito:"Viseu" },
  { municipio:"Moimenta de Maceira Dão", distrito:"Viseu" },
  { municipio:"Montemor-o-Novo", distrito:"Évora" },
  { municipio:"Montemor-o-Velho", distrito:"Coimbra" },
  { municipio:"Montijo", distrito:"Setúbal" },
  { municipio:"Mora", distrito:"Évora" },
  { municipio:"Mortágua", distrito:"Viseu" },
  { municipio:"Monção", distrito:"Viana do Castelo" },
  { municipio:"Melgaço", distrito:"Viana do Castelo" },
  { municipio:"Mealhada", distrito:"Aveiro" },
  { municipio:"Miranda do Corvo", distrito:"Coimbra" },
  { municipio:"Moimenta da Serra", distrito:"Guarda" },
  { municipio:"Murtosa", distrito:"Aveiro" },
  { municipio:"Mesquita", distrito:"Lisboa" },
  { municipio:"Mangualde", distrito:"Viseu" }
);
concelhosDistrito.push(
  { municipio:"Nelas", distrito:"Viseu" },
  { municipio:"Nisa", distrito:"Portalegre" },
  { municipio:"Nordeste", distrito:"Açores" },
  { municipio:"Oliveira de Azeméis", distrito:"Aveiro" },
  { municipio:"Oliveira de Frades", distrito:"Viseu" },
  { municipio:"Oliveira do Bairro", distrito:"Aveiro" },
  { municipio:"Oliveira do Hospital", distrito:"Coimbra" },
  { municipio:"Olhão", distrito:"Faro" },
  { municipio:"Ourém", distrito:"Santarém" },
  { municipio:"Ovar", distrito:"Aveiro" },
  { municipio:"Odemira", distrito:"Beja" },
  { municipio:"Palmela", distrito:"Setúbal" },
  { municipio:"Paços de Ferreira", distrito:"Porto" },
  { municipio:"Paredes", distrito:"Porto" },
  { municipio:"Paredes de Coura", distrito:"Viana do Castelo" },
  { municipio:"Pedrógão Grande", distrito:"Leiria" },
  { municipio:"Penacova", distrito:"Coimbra" },
  { municipio:"Penafiel", distrito:"Porto" },
  { municipio:"Penamacor", distrito:"Castelo Branco" },
  { municipio:"Penedono", distrito:"Viseu" },
  { municipio:"Penela", distrito:"Coimbra" },
  { municipio:"Pombal", distrito:"Leiria" },
  { municipio:"Ponta Delgada", distrito:"Açores" },
  { municipio:"Ponta do Sol", distrito:"Madeira" },
  { municipio:"Portalegre", distrito:"Portalegre" },
  { municipio:"Portel", distrito:"Évora" },
  { municipio:"Portimão", distrito:"Faro" },
  { municipio:"Porto", distrito:"Porto" },
  { municipio:"Porto Moniz", distrito:"Madeira" },
  { municipio:"Porto Santo", distrito:"Madeira" },
  { municipio:"Proença-a-Nova", distrito:"Castelo Branco" },
  { municipio:"Póvoa de Lanhoso", distrito:"Braga" },
  { municipio:"Póvoa de Varzim", distrito:"Porto" },
  { municipio:"Reguengos de Monsaraz", distrito:"Évora" },
  { municipio:"Resende", distrito:"Viseu" },
  { municipio:"Ribeira Brava", distrito:"Madeira" },
  { municipio:"Ribeira de Pena", distrito:"Vila Real" },
  { municipio:"Ribeira Grande", distrito:"Açores" },
  { municipio:"Rio Maior", distrito:"Santarém" },
  { municipio:"Sabugal", distrito:"Guarda" },
  { municipio:"Sabrosa", distrito:"Vila Real" },
  { municipio:"Salvaterra de Magos", distrito:"Santarém" },
  { municipio:"Santa Comba Dão", distrito:"Viseu" },
  { municipio:"Santa Cruz", distrito:"Madeira" },
  { municipio:"Santa Cruz da Graciosa", distrito:"Açores" },
  { municipio:"Santa Maria da Feira", distrito:"Aveiro" },
  { municipio:"Santana", distrito:"Madeira" },
  { municipio:"Santarém", distrito:"Santarém" },
  { municipio:"Santiago do Cacém", distrito:"Setúbal" },
  { municipio:"Santo Tirso", distrito:"Porto" },
  { municipio:"São Brás de Alportel", distrito:"Faro" },
  { municipio:"São João da Madeira", distrito:"Aveiro" },
  { municipio:"São João da Pesqueira", distrito:"Viseu" },
  { municipio:"São Pedro do Sul", distrito:"Viseu" },
  { municipio:"São Roque do Pico", distrito:"Açores" },
  { municipio:"Sernancelhe", distrito:"Viseu" },
  { municipio:"Serpa", distrito:"Beja" },
  { municipio:"Sertã", distrito:"Castelo Branco" },
  { municipio:"Setúbal", distrito:"Setúbal" },
  { municipio:"Seia", distrito:"Guarda" },
  { municipio:"Seixal", distrito:"Setúbal" },
  { municipio:"Silves", distrito:"Faro" },
  { municipio:"Sines", distrito:"Setúbal" },
  { municipio:"Sintra", distrito:"Lisboa" },
  { municipio:"Soure", distrito:"Coimbra" },
  { municipio:"Sátão", distrito:"Viseu" },
  { municipio:"Tarouca", distrito:"Viseu" },
  { municipio:"Tavira", distrito:"Faro" },
  { municipio:"Terras de Bouro", distrito:"Braga" },
  { municipio:"Tomar", distrito:"Santarém" },
  { municipio:"Tondela", distrito:"Viseu" },
  { municipio:"Torre de Moncorvo", distrito:"Bragança" },
  { municipio:"Torres Novas", distrito:"Santarém" },
  { municipio:"Torres Vedras", distrito:"Lisboa" },
  { municipio:"Trofa", distrito:"Porto" },
  { municipio:"Vagos", distrito:"Aveiro" },
  { municipio:"Vale de Cambra", distrito:"Aveiro" },
  { municipio:"Valença", distrito:"Viana do Castelo" },
  { municipio:"Valongo", distrito:"Porto" },
  { municipio:"Valpaços", distrito:"Vila Real" },
  { municipio:"Velas", distrito:"Açores" },
  { municipio:"Velho do Pico", distrito:"Açores" },
  { municipio:"Viana do Castelo", distrito:"Viana do Castelo" },
  { municipio:"Vidigueira", distrito:"Beja" },
  { municipio:"Vieira do Minho", distrito:"Braga" },
  { municipio:"Vila do Conde", distrito:"Porto" },
  { municipio:"Vila do Porto", distrito:"Açores" },
  { municipio:"Vila Franca de Xira", distrito:"Lisboa" },
  { municipio:"Vila Nova de Famalicão", distrito:"Braga" },
  { municipio:"Vila Nova de Foz Côa", distrito:"Guarda" },
  { municipio:"Vila Nova de Gaia", distrito:"Porto" },
  { municipio:"Vila Nova de Paiva", distrito:"Viseu" },
  { municipio:"Vila Nova de Poiares", distrito:"Coimbra" },
  { municipio:"Vila Pouca de Aguiar", distrito:"Vila Real" },
  { municipio:"Vila Real", distrito:"Vila Real" },
  { municipio:"Vila Real de Santo António", distrito:"Faro" },
  { municipio:"Vila Velha de Ródão", distrito:"Castelo Branco" },
  { municipio:"Vinhais", distrito:"Bragança" },
  { municipio:"Vizela", distrito:"Braga" },
  { municipio:"Vouzela", distrito:"Viseu" },
  { municipio:"Évora", distrito:"Évora" }
);
concelhosDistrito.push(
  // Madeira
  { municipio:"Funchal", distrito:"Madeira" },
  { municipio:"Santa Cruz", distrito:"Madeira" },
  { municipio:"Machico", distrito:"Madeira" },
  { municipio:"Santana", distrito:"Madeira" },
  { municipio:"São Vicente", distrito:"Madeira" },
  { municipio:"Calheta", distrito:"Madeira" },
  { municipio:"Porto Moniz", distrito:"Madeira" },
  { municipio:"Ponta do Sol", distrito:"Madeira" },
  { municipio:"Ribeira Brava", distrito:"Madeira" },
  { municipio:"Câmara de Lobos", distrito:"Madeira" },
  { municipio:"Porto Santo", distrito:"Madeira" },
// Açores
  { municipio:"Ponta Delgada", distrito:"Açores" },
  { municipio:"Lagoa", distrito:"Açores" },
  { municipio:"Ribeira Grande", distrito:"Açores" },
  { municipio:"Vila Franca do Campo", distrito:"Açores" },
  { municipio:"Nordeste", distrito:"Açores" },
  { municipio:"Povoação", distrito:"Açores" },
  { municipio:"Horta", distrito:"Açores" },
  { municipio:"Angra do Heroísmo", distrito:"Açores" },
  { municipio:"Praia da Vitória", distrito:"Açores" },
  { municipio:"Vila do Porto", distrito:"Açores" },
  { municipio:"Santa Cruz da Graciosa", distrito:"Açores" },
  { municipio:"São Roque do Pico", distrito:"Açores" },
  { municipio:"Lajes do Pico", distrito:"Açores" },
  { municipio:"Madalena do Pico", distrito:"Açores" },
  { municipio:"Velas", distrito:"Açores" },
  { municipio:"Calheta das Flores", distrito:"Açores" },
  { municipio:"Lajes das Flores", distrito:"Açores" },
  { municipio:"Corvo", distrito:"Açores" }
);
]
