- name: Commit e push
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add dados.json
    git diff --quiet || git commit -m "Atualizar dados ANEPC $(date +"%Y-%m-%d %H:%M")"
    git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
